name: Generate Snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake GIF
        uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: hackinghub2
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Debug Variables
        run: |
          echo "GIF output path: ${{ steps.snake-gif.outputs.gif_out_path }}"
          echo "SVG output path: ${{ steps.snake-gif.outputs.svg_out_path }}"

      - name: Check git status
        run: git status

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
